/**
 * Default modern icon mappings (Iconify IDs from the bundled catalog).
 * Users can override any key via modernIconSettings / toolbarIconSettings.
 */

export const DEFAULT_MODERN_ICONS: Record<string, string> = {
  public: "lucide:globe",
  private: "lucide:lock",
  protected: "lucide:shield",
  static: "lucide:pin",
  readonly: "lucide:eye",
  abstract: "lucide:shapes",
  async: "lucide:zap",
  export: "lucide:share-2",
  default: "lucide:star",
  constructor: "lucide:hammer",
  property: "lucide:tag",
  method: "lucide:cog",
  function: "lucide:square-function",
  getter: "lucide:arrow-up-from-line",
  setter: "lucide:arrow-down-to-line",
  class: "lucide:box",
  interface: "lucide:component",
  heading: "lucide:heading",
  variable: "lucide:variable",
  constant: "lucide:diamond",
  enum: "lucide:list",
  enumMember: "lucide:circle",
  module: "lucide:folder",
  namespace: "lucide:folder-open",
  typeAlias: "lucide:type",
  file: "lucide:file-text",
  object: "lucide:braces",
  array: "lucide:brackets",
  key: "lucide:key",
  event: "lucide:radio",
  operator: "lucide:plus",
  typeParameter: "lucide:baseline",
};

export const DEFAULT_TOOLBAR_ICONS: Record<string, string> = {
  refresh: "lucide:refresh-cw",
  collapseAll: "lucide:fold-vertical",
  editorOutline: "lucide:list-tree",
  sortPosition: "lucide:map-pin",
  sortName: "lucide:arrow-down-a-z",
  sortCategory: "lucide:layers",
  sortRelevance: "lucide:search",
  chevron: "lucide:chevron-right",
};

/** Default colors for outline icons (modern Lucide and Font Awesome). */
export const DEFAULT_ICON_COLORS: Record<string, string> = {
  public: "#22C55E",
  private: "#EF4444",
  protected: "#F59E0B",
  static: "#8B5CF6",
  readonly: "#06B6D4",
  abstract: "#A855F7",
  async: "#EAB308",
  export: "#3B82F6",
  default: "#FBBF24",
  constructor: "#F97316",
  property: "#38BDF8",
  method: "#C084FC",
  function: "#818CF8",
  getter: "#34D399",
  setter: "#FB7185",
  class: "#F59E0B",
  interface: "#60A5FA",
  heading: "#94A3B8",
  variable: "#67E8F9",
  constant: "#2DD4BF",
  enum: "#FB923C",
  enumMember: "#FCD34D",
  module: "#A78BFA",
  namespace: "#C4B5FD",
  typeAlias: "#4ADE80",
  file: "#94A3B8",
  object: "#F472B6",
  array: "#38BDF8",
  key: "#FBBF24",
  event: "#F87171",
  operator: "#A3E635",
  typeParameter: "#E879F9",
};

/** @deprecated Use DEFAULT_ICON_COLORS */
export const DEFAULT_MODERN_ICON_COLORS = DEFAULT_ICON_COLORS;

export const DEFAULT_FONTAWESOME_ICONS: Record<string, string> = {
  public: "fas fa-globe",
  private: "fas fa-lock",
  protected: "fas fa-shield-alt",
  static: "fas fa-thumbtack",
  readonly: "fas fa-book-open",
  abstract: "fas fa-theater-masks",
  async: "fas fa-bolt",
  export: "fas fa-share-square",
  default: "fas fa-star",
  constructor: "fas fa-hammer",
  property: "fas fa-tag",
  method: "fas fa-cog",
  function: "fas fa-wrench",
  getter: "fas fa-download",
  setter: "fas fa-upload",
  class: "fas fa-cube",
  interface: "fas fa-clipboard-list",
  heading: "fas fa-heading",
  variable: "fas fa-cube",
  constant: "fas fa-lock",
  enum: "fas fa-list-ol",
  enumMember: "fas fa-circle",
  module: "fas fa-folder",
  namespace: "fas fa-folder-open",
  typeAlias: "fas fa-tag",
  file: "fas fa-file",
  object: "fas fa-shapes",
  array: "fas fa-list",
  key: "fas fa-key",
  event: "fas fa-bolt",
  operator: "fas fa-plus",
  typeParameter: "fas fa-font",
};

/** Alternative icon suggestions shown in settings (must exist in catalog). */
export const MODERN_ICON_EXAMPLES: Record<string, string[]> = {
  public: ["lucide:globe", "lucide:radio", "lucide:eye"],
  private: ["lucide:lock", "lucide:key", "lucide:shield"],
  protected: ["lucide:shield", "lucide:lock", "lucide:pin"],
  static: ["lucide:pin", "lucide:map-pin", "lucide:diamond"],
  readonly: ["lucide:eye", "lucide:book-open", "lucide:lock"],
  abstract: ["lucide:shapes", "lucide:ghost", "lucide:sparkles"],
  async: ["lucide:zap", "lucide:infinity", "lucide:refresh-cw"],
  export: ["lucide:share-2", "lucide:upload", "lucide:arrow-up-from-line"],
  default: ["lucide:star", "lucide:sparkles", "lucide:circle-dot"],
  constructor: ["lucide:hammer", "lucide:wrench", "lucide:cog"],
  property: ["lucide:tag", "lucide:hash", "lucide:square"],
  method: ["lucide:cog", "lucide:wrench", "lucide:zap"],
  function: ["lucide:square-function", "lucide:variable", "lucide:braces"],
  getter: ["lucide:arrow-up-from-line", "lucide:download", "lucide:eye"],
  setter: ["lucide:arrow-down-to-line", "lucide:upload", "lucide:tag"],
  class: ["lucide:box", "lucide:component", "lucide:layers"],
  interface: ["lucide:component", "lucide:list-tree", "lucide:braces"],
  heading: ["lucide:heading", "lucide:hash", "lucide:type"],
  variable: ["lucide:variable", "lucide:box", "lucide:circle"],
  constant: ["lucide:diamond", "lucide:lock", "lucide:pin"],
  enum: ["lucide:list", "lucide:list-ordered", "lucide:layers"],
  enumMember: ["lucide:circle", "lucide:circle-dot", "lucide:square"],
  module: ["lucide:folder", "lucide:box", "lucide:layers"],
  namespace: ["lucide:folder-open", "lucide:layers", "lucide:folder"],
  typeAlias: ["lucide:type", "lucide:tag", "lucide:baseline"],
  file: ["lucide:file-text", "lucide:book-open", "lucide:text-cursor-input"],
  object: ["lucide:braces", "lucide:box", "lucide:shapes"],
  array: ["lucide:brackets", "lucide:list", "lucide:list-ordered"],
  key: ["lucide:key", "lucide:hash", "lucide:tag"],
  event: ["lucide:radio", "lucide:zap", "lucide:sparkles"],
  operator: ["lucide:plus", "lucide:hash", "lucide:baseline"],
  typeParameter: ["lucide:baseline", "lucide:type", "lucide:a-large-small"],
};

export const TOOLBAR_ICON_EXAMPLES: Record<string, string[]> = {
  refresh: ["lucide:refresh-cw", "lucide:infinity", "lucide:zap"],
  collapseAll: ["lucide:fold-vertical", "lucide:folder-minus", "lucide:list-tree"],
  editorOutline: ["lucide:list-tree", "lucide:layers", "lucide:folder"],
  sortPosition: ["lucide:map-pin", "lucide:list-ordered", "lucide:list-tree"],
  sortName: ["lucide:arrow-down-a-z", "lucide:a-large-small", "lucide:case-sensitive"],
  sortCategory: ["lucide:layers", "lucide:list-tree", "lucide:folder"],
  sortRelevance: ["lucide:search", "lucide:sparkles", "lucide:zap"],
  chevron: ["lucide:chevron-right", "lucide:plus", "lucide:circle"],
};
