/**
 * Default modern icon mappings (Iconify IDs from the bundled catalog).
 * Users can override any key via modernIconSettings / toolbarIconSettings.
 */

export const DEFAULT_MODERN_ICONS: Record<string, string> = {
  public: "lucide:globe",
  private: "lucide:lock",
  protected: "lucide:shield",
  static: "lucide:pin",
  readonly: "lucide:eye",
  abstract: "lucide:shapes",
  async: "lucide:zap",
  export: "lucide:share-2",
  default: "lucide:star",
  constructor: "lucide:hammer",
  property: "lucide:tag",
  method: "lucide:cog",
  function: "lucide:square-function",
  getter: "lucide:arrow-up-from-line",
  setter: "lucide:arrow-down-to-line",
  class: "lucide:box",
  interface: "lucide:component",
  heading: "lucide:heading",
  variable: "lucide:variable",
  constant: "lucide:diamond",
  enum: "lucide:list",
  enumMember: "lucide:circle",
  module: "lucide:folder",
  namespace: "lucide:folder-open",
  typeAlias: "lucide:type",
  file: "lucide:file-text",
  object: "lucide:braces",
  array: "lucide:brackets",
  key: "lucide:key",
  event: "lucide:radio",
  operator: "lucide:plus",
  typeParameter: "lucide:baseline",
};

export const DEFAULT_TOOLBAR_ICONS: Record<string, string> = {
  refresh: "lucide:refresh-cw",
  collapseAll: "lucide:fold-vertical",
  font: "lucide:type",
  sortPosition: "lucide:map-pin",
  sortName: "lucide:arrow-down-a-z",
  sortCategory: "lucide:layers",
  chevron: "lucide:chevron-right",
};

/** Alternative icon suggestions shown in settings (must exist in catalog). */
export const MODERN_ICON_EXAMPLES: Record<string, string[]> = {
  public: ["lucide:globe", "lucide:radio", "lucide:eye"],
  private: ["lucide:lock", "lucide:key", "lucide:shield"],
  protected: ["lucide:shield", "lucide:lock", "lucide:pin"],
  static: ["lucide:pin", "lucide:map-pin", "lucide:diamond"],
  readonly: ["lucide:eye", "lucide:book-open", "lucide:lock"],
  abstract: ["lucide:shapes", "lucide:ghost", "lucide:sparkles"],
  async: ["lucide:zap", "lucide:infinity", "lucide:refresh-cw"],
  export: ["lucide:share-2", "lucide:upload", "lucide:arrow-up-from-line"],
  default: ["lucide:star", "lucide:sparkles", "lucide:circle-dot"],
  constructor: ["lucide:hammer", "lucide:wrench", "lucide:cog"],
  property: ["lucide:tag", "lucide:hash", "lucide:square"],
  method: ["lucide:cog", "lucide:wrench", "lucide:zap"],
  function: ["lucide:square-function", "lucide:variable", "lucide:braces"],
  getter: ["lucide:arrow-up-from-line", "lucide:download", "lucide:eye"],
  setter: ["lucide:arrow-down-to-line", "lucide:upload", "lucide:tag"],
  class: ["lucide:box", "lucide:component", "lucide:layers"],
  interface: ["lucide:component", "lucide:list-tree", "lucide:braces"],
  heading: ["lucide:heading", "lucide:hash", "lucide:type"],
  variable: ["lucide:variable", "lucide:box", "lucide:circle"],
  constant: ["lucide:diamond", "lucide:lock", "lucide:pin"],
  enum: ["lucide:list", "lucide:list-ordered", "lucide:layers"],
  enumMember: ["lucide:circle", "lucide:circle-dot", "lucide:square"],
  module: ["lucide:folder", "lucide:box", "lucide:layers"],
  namespace: ["lucide:folder-open", "lucide:layers", "lucide:folder"],
  typeAlias: ["lucide:type", "lucide:tag", "lucide:baseline"],
  file: ["lucide:file-text", "lucide:book-open", "lucide:text-cursor-input"],
  object: ["lucide:braces", "lucide:box", "lucide:shapes"],
  array: ["lucide:brackets", "lucide:list", "lucide:list-ordered"],
  key: ["lucide:key", "lucide:hash", "lucide:tag"],
  event: ["lucide:radio", "lucide:zap", "lucide:sparkles"],
  operator: ["lucide:plus", "lucide:hash", "lucide:baseline"],
  typeParameter: ["lucide:baseline", "lucide:type", "lucide:a-large-small"],
};

export const TOOLBAR_ICON_EXAMPLES: Record<string, string[]> = {
  refresh: ["lucide:refresh-cw", "lucide:infinity", "lucide:zap"],
  collapseAll: ["lucide:fold-vertical", "lucide:folder-minus", "lucide:list-tree"],
  font: ["lucide:type", "lucide:case-sensitive", "lucide:a-large-small"],
  sortPosition: ["lucide:map-pin", "lucide:list-ordered", "lucide:list-tree"],
  sortName: ["lucide:arrow-down-a-z", "lucide:a-large-small", "lucide:case-sensitive"],
  sortCategory: ["lucide:layers", "lucide:list-tree", "lucide:folder"],
  chevron: ["lucide:chevron-right", "lucide:plus", "lucide:circle"],
};
